name: DonateCraft
version: 5.0.0
author: Gober
main: com.gmail.JyckoSianjaya.DonateCraft.Main.DonateCraft
description: Managing Donation has never been this easy!
commands:
   redeems:
     usage: /<command>
     aliases: [recoup, retrieve, code, rcode, redeemcode]
     description: Redeem your code!
   store:
     usage: /<command>
     description: Open the main store gui!
   donatecraft:
     usage: /<command>
     aliases: [dc, dcr]
     description: Use the donatecraft admin commands!
   cash:
     usage: /<command>
     aliases: [coin,coins]
     description: Check or manage cashes!
   acash:
     usage: /<command>
     aliases: [accash, accumulatedcash,acoin]
     description: Check your accumulated cash!